version: '3.8'

services:
  api-dotnet:
    build:
      context: ./Colectivo.Api
      dockerfile: Dockerfile
    image: api-dotnet:latest
    container_name: api-dotnet
    restart: always
    ports:
      - "5000:80"
    networks:
      - backend
    environment:
      ConnectionStrings__ColectivoDb=Server=172.18.0.2;Database=ColectivoDb;User Id=sa;Password=zrT15Itc21FsCv;TrustServerCertificate=True;Encrypt=False

networks:
  backend:
    external: true
